### ISSUE TITLE
Field width has not been initialized

### ISSUE THREAD

**Issue by alishahzad331** [mehedidew/internet_popup#1]
When is turn off the internet. I get this late initialization error that field "width" has not been initialized

**Comment by mehedidew** [comment]
The dialogue box doesn't have a fix width. Maybe the widget you're initializing it doesn't have a fix bound of height or width. You can try giving your widget a fix height or I can give a parameter for you to set one for the popup

**Comment by alishahzad331** [comment]
Yes. The widget doesn't have fixed height. Could you please give me a parameter one. Thanks

**Comment by alishahzad331** [comment]
Well I tried to initialize it in a widget which have fixed height and width but it did not work with it too

**Comment by mehedidew** [comment]
Ok.i will make a parameter for the widget. In the mean time, you can pass
your own widget as the popup.
